name: Manually build and deploy OpenData-Website
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Steps represent a sequence of tasks that will be executed as part of the job
    runs-on: ubuntu-latest
    steps:  
      - name: Bulid and deploy OpenData Website
        uses: robert-koch-institut/OpenData-Website@main
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   
