name: Manually sync Github Open Data repository and its metadata to OpenCoDE.de

on:
  workflow_dispatch:

jobs:
  sync_opencode:
    name: Sync Github Open Data repository and its metadata to OpenCoDE.de
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Open Data repository
        uses: robert-koch-institut/OpenData-Workflows/Sync_OpenData_repo_to_OpenCoDE@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENCODE_TOKEN: ${{ secrets.OPENCODE_TOKEN }}
          GROUP_ID: 2781
          ACCESS_USER: RKIOpenData
          # REPO_PATH: The repository name must not start or end with a special character and must not contain consecutive special characters
          ZENODOJSON_PATH: Metadaten/zenodo.json